# Generated by Django 5.2 on 2025-04-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_song_uploaded_by_alter_video_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_link_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
