# Generated by Django 5.2 on 2025-04-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_payment_checkout_url_payment_payment_link_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='access_tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro only'), ('PREMIUM', 'Premium only')], default='FREE', help_text='Who can listen: Free, Pro or Premium subscribers', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='access_tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro only'), ('PREMIUM', 'Premium only')], default='FREE', help_text='Who can watch: Free, Pro or Premium subscribers', max_length=10),
        ),
    ]
